### ISSUE TITLE
Responsive size of image is not unified when using the same image

### ISSUE THREAD

**Issue by leiz-me** [huiseoul/react-native-fit-image#74]
I got 2 types of item to show. 
Type A is only image, code like this,
```javascript
<ScrollView style={styles.container}>
  <View style={styles.itemDetailView}>
    <Lightbox>
      <View style={styles.itemImageOnlyView}>
        <FitImage source={{uri: this.state.imageUrl}} resizeMode="cover" style={styles.itemImageOnly} />
       </View>
    </Lightbox>
  </View>
</ScrollView>
```
[Type A, which I wanted](http://wx1.sinaimg.cn/large/62536167gy1fnlqihttiij20ku0tj42r.jpg)

Type B is text with image, code as below,
```javascript
<ScrollView style={styles.container}>
  <View style={styles.itemDetailView}>
    <View style={styles.itemContentView}>
      <Text>
        {this.state.content}
      </Text>
    </View>
    <Lightbox>
      <View style={styles.itemImageView}>
        <FitImage source={{uri: this.state.imageUrl}} resizeMode="cover" style={styles.itemImage} />
      </View>
    </Lightbox>
  </View>
</ScrollView>
```
[Type B, I wanted it looks like A with Text above image instead of a square area](http://wx3.sinaimg.cn/large/62536167gy1fnlqihkzf1j20ku0mdtbu.jpg)

These 2 types of image view has the same style settings.
```css
  itemImageOnlyView: {
  },
  itemImageOnly: {
    width: undefined,
    height: undefined,
    margin: 10
  },
  itemImageView: {
  },
  itemImage: {
    width: undefined,
    height: undefined,
    margin: 10
  },
```
However I got 2 different sizes of images.
Type A I got a square image displaying view and Type B I got a rectangle image displaying view which is expected.  The image sources are the same.

Does anyone can give me a hint that what is going here?
I want to make these 2 types of image output as the same rectangle one.
Thank you.

*******
More Info
******
```javascript
  constructor(props) {
    super(props)
    this.state = {
      ...
      content: '',
      imageUrl: "http://via.placeholder.com/200X200",
      ...
    }
  }
```
I had an initial imageUrl with size 200X200, that's exactly the same size of the square area.
